import { Badge, Box, Button, Center, Flex, Grid, Heading, Progress, SimpleGrid, Stack, Text } from '@chakra-ui/react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { AlertTriangle, ArrowDownRight, ArrowUpRight, CreditCard, Landmark, PiggyBank, Plus, Target, WalletCards } from 'lucide-react';
import type { FinanceRecord, FinanceTable } from '../../types/database';
import { calculateFinancialSnapshot, type FinanceData } from '../../services/financialEngine';
import { formatCurrency } from '../../utils/formatters';

const palette=['#0F62FE','#6C3BFF','#35c894','#f7b84b','#f56565','#38b2ac'];
const panel={bg:'panel',border:'1px solid',borderColor:'line',borderRadius:'2xl',boxShadow:'card'} as const;
const ChartBox=({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode})=><Box {...panel} p="20px" minH="320px"><Heading size="sm">{title}</Heading><Text color="muted" fontSize="sm">{subtitle}</Text><Box h="245px" mt="4">{children}</Box></Box>;

export default function Dashboard({data,onNavigate}:{data:Record<FinanceTable,FinanceRecord[]>;onNavigate:(page:'despesas'|'metas')=>void}){
 const snapshot=calculateFinancialSnapshot(data as FinanceData);const cards=[
  ['Saldo disponível',snapshot.availableBalance,<WalletCards/>,snapshot.availableBalance>=0?'Caixa livre atual':'Saldo negativo'],
  ['Receitas recebidas',snapshot.received,<ArrowUpRight/>,`Previstas: ${formatCurrency(snapshot.predictedRevenue)}`],
  ['Despesas pagas',snapshot.paidExpenses,<ArrowDownRight/>,`Pendentes: ${formatCurrency(snapshot.pendingExpenses)}`],
  ['Faturas em aberto',snapshot.openInvoiceTotal,<CreditCard/>,`${data.faturas_cartao.filter(x=>x.status!=='paga').length} fatura(s)`],
  ['Guardado em metas',snapshot.goalsTotal,<Target/>,`${data.metas_financeiras.length} objetivo(s)`],
  ['Total investido',snapshot.investedTotal,<Landmark/>,`${data.investimentos.length} ativo(s)`],
  ['Patrimônio total',snapshot.patrimony,<PiggyBank/>, 'Saldo + metas + investimentos'],
  ['Economia do mês',snapshot.economy,<PiggyBank/>,`${snapshot.savingsRate.toFixed(1)}% da renda`],
 ];
 return <><Flex justify="space-between" align={{base:'flex-start',md:'center'}} direction={{base:'column',md:'row'}} gap="4" mb="7"><Box><Heading size="lg">Sua central financeira</Heading><Text color="muted" mt="1">Caixa, patrimônio e compromissos conectados em tempo real.</Text></Box><Button leftIcon={<Plus size={17}/>} onClick={()=>onNavigate('despesas')}>Nova movimentação</Button></Flex>
 <SimpleGrid columns={{base:1,sm:2,xl:4}} spacing="14px">{cards.map(([label,value,icon,help],index)=><Box key={String(label)} {...panel} p="19px"><Flex justify="space-between" color={index===2||index===3?'orange.300':index===1?'green.300':'brand.300'}><Text color="muted" fontSize="sm">{label}</Text>{icon}</Flex><Heading size="md" mt="3">{formatCurrency(Number(value))}</Heading><Text color="muted" fontSize="xs" mt="1">{help}</Text></Box>)}</SimpleGrid>
 <Grid templateColumns={{base:'1fr',xl:'1.5fr 1fr'}} gap="16px" mt="4"><ChartBox title="Receitas x saídas" subtitle="Despesas e faturas pagas nos últimos seis meses"><ResponsiveContainer><BarChart data={snapshot.timeline}><CartesianGrid strokeDasharray="4 4" stroke="#252b36" vertical={false}/><XAxis dataKey="label"/><YAxis tickFormatter={v=>`${v/1000}k`}/><Tooltip formatter={v=>formatCurrency(Number(v))}/><Legend/><Bar dataKey="receitas" fill="#0F62FE" radius={[5,5,0,0]}/><Bar dataKey="despesas" fill="#6C3BFF" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></ChartBox><ChartBox title="Gastos por categoria" subtitle="Somente despesas pagas neste mês">{snapshot.categories.length?<ResponsiveContainer><PieChart><Pie data={snapshot.categories} dataKey="value" innerRadius={55} outerRadius={85} paddingAngle={3}>{snapshot.categories.map((item,index)=><Cell key={item.name} fill={palette[index%palette.length]}/>)}</Pie><Tooltip formatter={v=>formatCurrency(Number(v))}/><Legend/></PieChart></ResponsiveContainer>:<Center h="full" color="muted">Sem despesas pagas no período.</Center>}</ChartBox></Grid>
 <Grid templateColumns={{base:'1fr',xl:'1.5fr 1fr'}} gap="16px" mt="4"><ChartBox title="Evolução patrimonial" subtitle="Saldo disponível comparado ao patrimônio"><ResponsiveContainer><AreaChart data={snapshot.timeline}><CartesianGrid strokeDasharray="4 4" stroke="#252b36" vertical={false}/><XAxis dataKey="label"/><YAxis hide/><Tooltip formatter={v=>formatCurrency(Number(v))}/><Legend/><Area type="monotone" dataKey="patrimonio" stroke="#6C3BFF" fill="#6C3BFF" fillOpacity=".12" strokeWidth={3}/><Area type="monotone" dataKey="saldo" stroke="#0F62FE" fill="#0F62FE" fillOpacity=".1" strokeWidth={2}/></AreaChart></ResponsiveContainer></ChartBox><Box {...panel} p="20px"><Flex justify="space-between"><Box><Heading size="sm">Metas financeiras</Heading><Text color="muted" fontSize="sm">Progresso consolidado</Text></Box><Button size="xs" variant="ghost" onClick={()=>onNavigate('metas')}>Ver todas</Button></Flex><Stack mt="5" spacing="5">{data.metas_financeiras.slice(0,4).map(meta=>{const progress=(meta.valor_atual??0)/(meta.valor_alvo||1)*100;return <Box key={meta.id}><Flex justify="space-between"><Text fontSize="sm" fontWeight="600">{meta.nome}</Text><Text fontSize="xs">{progress.toFixed(0)}%</Text></Flex><Progress value={progress} mt="2" borderRadius="full"/><Text fontSize="xs" color="muted" mt="1">{formatCurrency(meta.valor_atual)} de {formatCurrency(meta.valor_alvo)}</Text></Box>})}{!data.metas_financeiras.length&&<Center h="180px" color="muted">Nenhuma meta cadastrada.</Center>}</Stack></Box></Grid>
 <Grid templateColumns={{base:'1fr',lg:'1fr 1fr'}} gap="4" mt="4"><Box {...panel} p="20px"><Flex justify="space-between" mb="4"><Box><Heading size="sm">Alertas inteligentes</Heading><Text color="muted" fontSize="sm">O que pede sua atenção agora</Text></Box><AlertTriangle color="#f7b84b"/></Flex><Stack>{snapshot.alerts.slice(0,6).map((alert,index)=><Flex key={`${alert.title}-${index}`} bg="panel2" p="3" borderRadius="xl" gap="3"><AlertTriangle size={17} color={alert.type==='danger'?'#f56565':'#f7b84b'}/><Box><Text fontSize="sm" fontWeight="700">{alert.title}</Text><Text fontSize="xs" color="muted">{alert.description}</Text></Box></Flex>)}{!snapshot.alerts.length&&<Text color="muted" fontSize="sm">Tudo tranquilo por aqui.</Text>}</Stack></Box><Box {...panel} p="20px"><Heading size="sm">Comprometimento da renda</Heading><Text color="muted" fontSize="sm">Despesas e faturas previstas sobre a receita prevista</Text><Heading mt="5" size="xl">{snapshot.incomeCommitment.toFixed(1)}%</Heading><Progress value={snapshot.incomeCommitment} colorScheme={snapshot.incomeCommitment>80?'red':snapshot.incomeCommitment>60?'orange':'blue'} mt="4" h="10px" borderRadius="full"/><Flex justify="space-between" mt="3"><Badge colorScheme="orange">{formatCurrency(snapshot.pendingExpenses)} pendente</Badge><Badge colorScheme="purple">{formatCurrency(snapshot.openInvoiceTotal)} em faturas</Badge></Flex></Box></Grid></>
}
